
target-version = "py310"
fix = true
line-length = 120
indent-width = 4

[lint]
extend-select = [
    "B",
    "C90",
    "E501",  # line too long (default 88)
    "I",  # isort
    "UP",  # pyupgrade
]
extend-ignore = [
    "B023",
    "UP007",  # use | for type annotations
    "F821",  # undefined name
]
exclude = ["setup/*"]

[format]
exclude = ["setup/*", "*.yml"]
quote-style = "double"
indent-style = "space"

[lint.per-file-ignores]
"__init__.py" = ["I001", "F401"]  # ignore unused and unsorted imports in __init__.py
"__manifest__.py" = ["B018"]  # useless expression

[lint.isort]
section-order = ["future", "standard-library", "third-party", "odoo", "odoo-addons", "first-party", "local-folder"]

[lint.isort.sections]
"odoo" = ["odoo"]
"odoo-addons" = ["odoo.addons"]

[lint.mccabe]
max-complexity = 16
